channels:
  - conda-forge
  - defaults
dependencies:
  - basemap
  - pip:
    - seaborn==0.8.1
    - pandas==0.21.1
    - matplotlib==2.1.1
    - geonamescache==0.21
    - numpy==1.13.3
    - pycountry==17.9.23
    - xlrd
